[server_web]
external_url = 'http://172.18.0.1:8000'
bind_host = '0.0.0.0'
bind_port = 8000
# num_workers = 4

[server_master]
external_url = 'tcp://cc-server-master:8001'
bind_host = '0.0.0.0'
bind_port = 8001
scheduling_interval_seconds = 60

[server_log]
external_url = 'tcp://cc-server-log:8002'
bind_host = '0.0.0.0'
bind_port = 8002
log_dir = '~/.cc_server/logs/'
suppress_stdout = true

[server_files]
external_url = 'http://172.18.0.1:8003'
bind_host = '0.0.0.0'
bind_port = 8003
input_files_dir = '~/.cc_server/input_files'
result_files_dir = '~/.cc_server/result_files'
# num_workers = 4

[mongo]
username = 'ccdbAdmin'
password = 'PASSWORD'
host = 'mongo'
port = 27017
db = 'ccdb'

[docker]
thread_limit = 8
api_timeout = 30
# docker_machine_dir = '~/.docker/machine'

[docker.nodes.dind]
base_url = 'dind:2375'

[defaults.application_container_description]
entry_point = 'python3 -m cc_container_worker.application_container'

[defaults.data_container_description]
image = 'docker.io/curiouscontainers/cc-image-fedora:0.12'
entry_point = 'python3 -m cc_container_worker.data_container'
container_ram = 512
# num_workers = 4

[defaults.inspection_container_description]
image = 'docker.io/curiouscontainers/cc-image-fedora:0.12'
entry_point = 'python3 -m cc_container_worker.inspection_container'

[defaults.scheduling_strategies]
container_allocation = 'spread'

[defaults.error_handling]
max_task_trials = 3

[defaults.authorization]
num_login_attempts = 3
block_for_seconds = 120
tokens_valid_for_seconds = 172800
