version: "2"
services:
  cc-server:
    build: ./cc-server
    command: "bash /home/cc/.config/curious-containers/cc-server/init.sh"
    ports:
      - "5000:80"
    volumes:
      - ../../cc_server:/home/cc/cc-server/cc_server
      - ../../cc_commons:/home/cc/cc-server/cc_commons
      - .:/home/cc/.config/curious-containers
      #- ~/.docker/machine/machines:/home/cc/.docker/machine/machines
      #- ~/.cc_server:/home/cc/.cc_server
    links:
      - mongo
      - dind
    depends_on:
      - mongo-seed
  mongo:
    image: mongo
  mongo-seed:
    build: ./mongo-seed
    volumes:
      - .:/root/.config/curious-containers
    command: "python3 /root/.config/curious-containers/mongo-seed/init.py"
    links:
      - mongo
  dind:
    image: docker:dind
    privileged: true
    command: "docker daemon -H tcp://0.0.0.0:2375"

