# see documentation for configuration instructions
# ------------------------------------------------

[server_web]
external_url = 'http://172.17.0.1:8000'
bind_host = '0.0.0.0'
bind_port = 8000

[server_master]
external_url = 'tcp://localhost:8001'
bind_host = '0.0.0.0'
bind_port = 8001
scheduling_interval_seconds = 60

[server_log]
external_url = 'tcp://localhost:8002'
bind_host = '0.0.0.0'
bind_port = 8002
log_dir = '~/.cc_server/logs/'
suppress_stdout = false

[mongo]
username = 'ccdbAdmin'
password = 'PASSWORD'
host = 'localhost'
port = 27017
db = 'ccdb'

[docker]
thread_limit = 8
api_timeout = 30

[docker.nodes.local]
base_url = 'unix://var/run/docker.sock'

[defaults.application_container_description]
entry_point = 'python3 /opt/container_worker'

[defaults.data_container_description]
image = 'docker.io/curiouscontainers/cc-image-ubuntu'
entry_point = 'python3 /opt/container_worker'
container_ram = 512

# Only necessary if data container image is in private registry
# [defaults.data_container_description.registry_auth]
# username = 'REGISTRY_USER'
# password = 'PASSWORD'

[defaults.scheduling_strategies]
container_allocation = 'spread'

[defaults.error_handling]
max_task_trials = 3
dead_node_invalidation = false

[defaults.authorization]
num_login_attempts = 3
block_for_seconds = 120
tokens_valid_for_seconds = 172800
