#!/usr/bin/env bash

services=(cc-server-web cc-server-master cc-server-log mongo-seed mongo dind registry)

for service in "${services[@]}"
do
    echo "Service: ${service}"
    docker-compose kill ${service}
    docker-compose rm -f ${service}
    echo ""
done
