[server]
host = 'http://172.18.0.1:5000'
internal_port = 5000
log_dir = '~/.cc_server/'

[mongo]
username = 'ccdbAdmin'
password = 'PASSWORD'
host = 'mongo'
dbname = 'ccdb'

[docker]
thread_limit = 8
base_url = 'dind:2375'

[defaults.data_container_description]
image = 'docker.io/curiouscontainers/cc-image-fedora'
entry_point = 'python3 /opt/container_worker'
container_ram = 512

[defaults.scheduling_strategies]
container_allocation = 'spread'

[defaults.error_handling]
max_task_trials = 3

[defaults.authorization]
num_login_attempts = 3
block_for_seconds = 120
tokens_valid_for_seconds = 172800
