[server_web]
external_url = 'http://172.18.0.1:8000'
bind_host = '0.0.0.0'
bind_port = 8000
# num_workers = 4

[server_master]
external_url = 'tcp://cc-server-master:8001'
bind_host = '0.0.0.0'
bind_port = 8001
scheduling_interval_seconds = 60

[server_log]
external_url = 'tcp://cc-server-log:8002'
bind_host = '0.0.0.0'
bind_port = 8002
log_dir = '~/.cc_server/logs/'
suppress_stdout = true

[mongo]
username = 'ccdbAdmin'
password = 'PASSWORD'
host = 'mongo'
port = 27017
db = 'db'

[docker]
thread_limit = 8
api_timeout = 30
# machines_dir = '~/.docker/machine/machines'

[docker.nodes.dind]
base_url = 'dind:2375'

[defaults.application_container_description]
entry_point = 'python3 /opt/container_worker'

[defaults.data_container_description]
image = 'docker.io/curiouscontainers/cc-image-ubuntu'
entry_point = 'python3 /opt/container_worker'
container_ram = 512
# num_workers = 4

[defaults.scheduling_strategies]
container_allocation = 'spread'

[defaults.error_handling]
max_task_trials = 3

[defaults.authorization]
num_login_attempts = 3
block_for_seconds = 120
tokens_valid_for_seconds = 172800
