version: "2"
services:
  cc-server-web:
    build: ./cc-server-image
    command: "python3 -u -m cc_server.web_service"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./config.toml:/root/.config/cc-server/config.toml:ro
      - ../cc_server:/opt/cc_server:ro
    links:
      - mongo
      - cc-server-master
      - cc-server-log
    tty: true

  cc-server-master:
    build: ./cc-server-image
    command: "python3 -u -m cc_server.master_service"
    volumes:
      - ./config.toml:/root/.config/cc-server/config.toml:ro
      - ../cc_server:/opt/cc_server:ro
      - ~/.docker/machine:/root/.docker/machine:ro
    links:
      - mongo
      - dind
      - cc-server-log
    depends_on:
      - mongo-seed
    tty: true

  cc-server-log:
    build: ./cc-server-image
    command: "python3 -u -m cc_server.log_service"
    volumes:
      - ./config.toml:/root/.config/cc-server/config.toml:ro
      - ../cc_server:/opt/cc_server:ro
      - ~/.cc_server_compose/logs:/root/.cc_server/logs
    tty: true

  mongo:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ~/.cc_server_compose/mongo/db:/data/db
    tty: true

  mongo-seed:
    build: ./mongo-seed
    volumes:
      - ./config.toml:/root/.config/cc-server/config.toml:ro
      - ./mongo-seed/mongo_seed:/opt/mongo_seed
    command: "python3 -u -m mongo_seed"
    links:
      - mongo
    tty: true

  dind:
    image: docker:dind
    privileged: true
    command: "dockerd --insecure-registry=registry:5000 -H tcp://0.0.0.0:2375"
    volumes:
      - ~/.cc_server_compose/dind/docker:/var/lib/docker
    links:
      - registry
      - file-server
    tty: true

  file-server:
    build: ./cc-server-image
    command: "gunicorn -w 4 -b 0.0.0.0:6000 file_server.__main__:app"
    ports:
      - "127.0.0.1:6000:6000"
    volumes:
      - ./file_server:/opt/file_server:ro
      - ~/.cc_server_compose/input_files:/root/input_files:ro
      - ~/.cc_server_compose/result_files:/root/result_files
    tty: true

  registry:
    image: registry:2
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ~/.cc_server_compose/registry/data:/data
