version: "2"
services:
  cc-server:
    build: ./cc-server
    command: "python3 -u /root/.config/curious-containers/cc-server/init.py"
    ports:
      - "5000:5000"
    volumes:
      - ../../cc_server:/opt/cc_server
      - ../../cc_commons:/opt/cc_commons
      - .:/root/.config/curious-containers
      #- ./logs:/root/.cc_server
    links:
      - mongo
      - dind
    depends_on:
      - mongo-seed
  mongo:
    image: mongo
  mongo-seed:
    build: ./mongo-seed
    volumes:
      - .:/root/.config/curious-containers
    command: "python3 /root/.config/curious-containers/mongo-seed/init.py"
    links:
      - mongo
  dind:
    image: docker:dind
    privileged: true
    command: "docker daemon -H tcp://0.0.0.0:2375"

