#!/usr/bin/env python3

import os
import sys
from getpass import getpass

sys.path.insert(0, os.path.split(os.path.split(os.path.abspath(__file__))[0])[0])

from cc_commons.authorization import Authorize
from cc_commons.database import Mongo

from cc_commons.configuration import Config

config = Config()

mongo = Mongo(
    config=config
)
auth_handler = Authorize(
    config=config,
    tee=print,
    mongo=mongo
)

print('You are in the process of creating a user account.')
print('ATTENTION: an already existing user with the exact same username will be updated with new settings!')
input('Hit [ENTER] to proceed...')
username = input('Username: ')
if not username:
    print('ABORT: username must not be empty.')
    exit(1)
password = getpass('Password: ')
if not password:
    print('ABORT: password must not be empty.')
is_admin = input('Grant admin rights [y/N]: ')
is_admin = is_admin.lower()
is_admin = is_admin == 'yes' or is_admin == 'y'
if is_admin:
    print('Admin rights GRANTED!')
else:
    print('Admin rights NOT granted!')

auth_handler.create_user(username, password, is_admin=is_admin)

print('Done!')
