#!/usr/bin/env python3

import sys
import os

sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..'))

from cc_server.configuration import Config
from cc_server.database import Mongo

conf_file_path = None
try:
    conf_file_path = sys.argv[1]
except:
    pass

config = Config(conf_file_path)
mongo = Mongo(
    config=config
)

delete_collections = [
    'tasks',
    'task_groups',
    'application_containers',
    'data_containers',
    'block_entries',
    'tracing',
    'dead_nodes'
]
preserve_collections = [
    'users'
]

print('You are in the process of DELETING the following database collections:')
for c in delete_collections:
    print('*', c)
print('You are NOT deleting the following database collections:')
for c in preserve_collections:
    print('*', c)

input('Hit [ENTER] to proceed...')

mongo.drop_db_collections(delete_collections)

print('Done!')
