#!/usr/bin/env python3

import os
import sys

sys.path.insert(0, os.path.split(os.path.split(os.path.abspath(__file__))[0])[0])

from cc_commons.database import Mongo

from cc_commons.configuration import Config


config = Config()

mongo = Mongo(
    config=config
)

delete_collections = [
    'tasks',
    'task_groups',
    'application_containers',
    'data_containers',
    'block_entries',
    'dead_nodes'
]
preserve_collections = [
    'users'
]

print('You are in the process of DELETING the following database collections:')
for c in delete_collections:
    print('*', c)
print('You are NOT deleting the following database collections:')
for c in preserve_collections:
    print('*', c)

input('Hit [ENTER] to proceed...')

mongo.drop_db_collections(delete_collections)

print('Done!')
